overrides:
  brace-expansion: ^2.0.2
  glob: ^11.0.0
  tar: ^7.5.7

allowBuilds:
  bufferutil: true
  cypress: true
  electron: true
  electron-winstaller: true
  esbuild: true
  register-scheme@https://codeload.github.com/devsnek/node-register-scheme/tar.gz/e7cc9a63a1f512565da44cb57316d9fb10750e17: false
  utf-8-validate: true
